name: Generate Advanced Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  generate:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: RazorRSD
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
          
          # Color options for the snake
          color_snake: '#1a237e'
          
          # Configuration for the animation
          trace_length: 12
          framerate: 20
          max_speed: 3
          min_speed: 1
          
          # Contribution colors from light to dark
          color_dots: |
            #4169E1,
            #0000FF,
            #0000CD,
            #00008B,
            #000080

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
